In [1]:
# Importing Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# Importing Dataset
df = pd.read_csv('tvmarketing.csv')

In [3]:
# Showing the first 5th
df.head()

      TV  Sales
0  230.1   22.1
1   44.5   10.4
2   17.2    9.3
3  151.5   18.5
4  180.8   12.9

In [4]:
# Showing the 5th latest
df.tail()

        TV  Sales
195   38.2    7.6
196   94.2    9.7
197  177.0   12.8
198  283.6   25.5
199  232.1   13.4

In [5]:
# Information About Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TV      200 non-null    float64
 1   Sales   200 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB

In [6]:
# Descriptive Statistics
df.describe()

               TV       Sales
count  200.000000  200.000000
mean   147.042500   14.022500
std     85.854236    5.217457
min      0.700000    1.600000
25%     74.375000   10.375000
50%    149.750000   12.900000
75%    218.825000   17.400000
max    296.400000   27.000000

In [7]:
# Initialize the Feature and Target Variable
x = df['TV'].values.reshape(-1, 1)
y = df['Sales'].values.reshape(-1, 1)

In [8]:
# Train Test Splitting
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = .7, test_size = .3)

In [9]:
# Initialize Normalizer into norm variable
norm = Normalizer()

In [10]:
# initialize Normalizer for feature & Target
norm_x = norm
norm_y = norm

In [11]:
# Scaling train and test feature and target
x_train_scaler = norm_x.fit_transform(x_train)
x_test_scaler = norm_x.transform(x_test)
y_train_scaler = norm_y.fit_transform(y_train)
y_test_scaler = norm_y.transform(y_test)

In [12]:
# Initialize model with 5 nearest neighbors
knn = KNeighborsRegressor(n_neighbors = 5)

In [13]:
# fit and training the train data that already scaled before
model = knn.fit(x_train_scaler, y_train_scaler)

In [14]:
# testing the test data
y_pred = model.predict(x_test_scaler)

In [15]:
# function for metrics
def mae(y_pred, y_test):
    '''
    Compute the mean absolute error with predict and testing data
    '''
    return mean_absolute_error(y_pred, y_test)

def mse(y_pred, y_test):
    '''
    Compute the mean squared error with predict and testing data
    '''
    return mean_squared_error(y_pred, y_test)

def r2(y_pred, y_test):
    '''
    Compute the r2 score
    '''
    return r2_score(y_pred, y_test)

In [16]:
# Result of testing
print('Mean Absolute Error:', mae(y_pred, y_test_scaler))
print('Mean Squared Error:', mse(y_pred, y_test_scaler))
print('R2 Score:', r2(y_pred, y_test_scaler))

Mean Absolute Error: 0.0
Mean Squared Error: 0.0
R2 Score: 1.0